# Generated by Django 4.1.3 on 2022-11-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cancion', '0001_initial'),
        ('artista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escriben',
            fields=[
                ('id_escriben', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fk_artista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artista.artista')),
                ('fk_cancion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cancion.cancion')),
            ],
        ),
    ]
