# Generated by Django 4.1.3 on 2022-11-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id_cancion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=30)),
                ('letra', models.CharField(max_length=10000)),
            ],
        ),
    ]
